#
#   ___        _               _  _         _
#  / __|  _ __| |_ ___ _ __   | || |_  _ __| |
# | (_| || (_-<  _/ _ \ '  \  | __ | || / _` |
#  \___\_,_/__/\__\___/_|_|_| |_||_|\_,_\__,_|
#

#Text you will see on the server, {tps}, {load}, {players}, {max_players}, {line}, {x} {y} {z}, {coins}, {MOTD}, {faction}, {name}, {time}, {kills}, {deaths}, {ping}, {group}, {itemid}, {itemeta}, {client-ip}, {server-ip}, {uptime} and & for color
#{coins} You need to use EconomyAPI to show money!

#Text to show on the server in the custom bar!
text: "§b-=-+-=-| §a§lFunny §l§aBlock§r §7[§a{players}§7/§a{max_players}§7] §b|-=-+-=-{line}§bNick: §a{name}§6 | §bRank: §d%{group}{line}§bXu: §e${coins}§6 | §bFaction: §2{faction}{line}&bPing:&r {ping}ms"

#Time that the message is updated, P.S Leave the default 5!
time: 5

#TimeZones configuration, link: https://www.timeanddate.com/time/zones , Default timezone Central European!
timezone: CET

#TimeZones Format Configuration Example (H:i) Format 24 hours (h:i A) Format 12 hours, Default formatime 24 hours!
formatime: H:i